'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Copy, Download, Feather, FileText, FolderHeart, LayoutGrid, List, LoaderCircle, Menu, MoreHorizontal, Plus, Search, Shield, Sparkles, Swords, Trash2, Upload, Users, WandSparkles, X, ScrollText, Backpack, Heart, Mountain, Save } from 'lucide-react';
import type { Catalog, Character, Entity } from '@/lib/types';
import { deriveCharacter, createCharacter, withHistory } from '@/lib/engine';
import { LocalCharacterRepository, exportJSON, importJSON } from '@/lib/persistence';
import { createDemo } from '@/lib/demo';
import { Logo, Button, ClassIcon, Modal, SourceTag, Empty, cleanDescription, downloadText } from './ui';
import { CharacterWizard } from './wizard';
import { CharacterSheet } from './sheet';
import { CatalogView } from './reference';

export const SHEET_SECTIONS=[{id:'Resumen',icon:LayoutGrid},{id:'Combate',icon:Swords},{id:'Habilidades',icon:Shield},{id:'Rasgos',icon:Sparkles},{id:'Inventario',icon:Backpack},{id:'Hechizos',icon:WandSparkles},{id:'Biografía',icon:Feather},{id:'Notas',icon:FileText},{id:'Progresión',icon:Mountain}];
const REFERENCE_SECTIONS=[{id:'Razas y linajes',icon:Users},{id:'Clases',icon:Swords},{id:'Hechizos',icon:WandSparkles},{id:'Dotes',icon:Sparkles},{id:'Trasfondos',icon:ScrollText},{id:'Equipo',icon:Backpack}];
type View='library'|'wizard'|'sheet'|'catalog'|'source';

export function GrimorioApp(){
  const [catalog,setCatalog]=useState<Catalog|null>(null),[characters,setCharacters]=useState<Character[]>([]),[view,setView]=useState<View>('library'),[activeId,setActiveId]=useState(''),[section,setSection]=useState('Resumen'),[reference,setReference]=useState('Razas y linajes'),[mobile,setMobile]=useState(false),[saved,setSaved]=useState<'saved'|'saving'|'error'>('saved');
  const [loadError,setLoadError]=useState(''),[toast,setToast]=useState<{text:string;error?:boolean}|null>(null),[deleteId,setDeleteId]=useState(''),[searchOpen,setSearchOpen]=useState(false),[globalQuery,setGlobalQuery]=useState(''),[detail,setDetail]=useState<Entity|null>(null),[draft,setDraft]=useState<Character|null>(null);
  const repo=useRef<LocalCharacterRepository|null>(null),importInput=useRef<HTMLInputElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const notify=(text:string,error=false)=>{if(toastTimer.current)clearTimeout(toastTimer.current);setToast({text,error});toastTimer.current=setTimeout(()=>setToast(null),5000)};
  useEffect(()=>{let alive=true;fetch('/api/catalog').then(r=>{if(!r.ok)throw new Error('No se pudo cargar el catálogo.');return r.json() as Promise<Catalog>}).then(async data=>{
    const repository=new LocalCharacterRepository(data);repo.current=repository;
    await repository.seedIfEmpty(createDemo(data)); const list=await repository.list();
    if(alive){setCatalog(data);setCharacters(list)}
  }).catch(e=>{if(alive)setLoadError(e instanceof Error?e.message:'No se pudo abrir el grimorio.');});return()=>{alive=false}},[]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(v=>!v)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
  const persist=async(c:Character)=>{const updated={...c,updatedAt:new Date().toISOString()};setCharacters(cs=>cs.some(x=>x.id===updated.id)?cs.map(x=>x.id===updated.id?updated:x):[updated,...cs]);setSaved('saving');try{await repo.current!.save(updated);setSaved('saved');return true}catch(e){setSaved('error');notify(e instanceof Error?e.message:'No se pudo guardar. Exporta una copia para conservar tus cambios.',true);return false}};
  const navigate=(next:View)=>{setView(next);setMobile(false);window.scrollTo({top:0,behavior:'instant'})};
  const open=(c:Character)=>{setActiveId(c.id);setSection('Resumen');navigate('sheet')};
  const begin=()=>{setDraft(createCharacter());navigate('wizard')};
  const active=characters.find(c=>c.id===activeId);
  const duplicate=async(c:Character)=>{const copy=structuredClone(c);copy.id=crypto.randomUUID();copy.name=c.name+' (copia)';copy.createdAt=new Date().toISOString();copy.isDemo=false;delete copy.lastLevelSnapshot;if(await persist(withHistory(copy,'Duplicado de '+c.name)))notify('Personaje duplicado.')};
  const exportOne=(c:Character)=>{downloadText(exportJSON(c),c.name.replace(/[^\p{L}\p{N} -]/gu,'')+'.json');notify('Personaje exportado.')};
  const importFile=async(file?:File)=>{if(!file||!catalog)return;try{if(file.size>5*1024*1024)throw new Error('El archivo supera el límite de 5 MB.');const c=importJSON(await file.text(),catalog);c.id=crypto.randomUUID();c.ownerId='local';c.isDemo=false;if(c.lastLevelSnapshot){const snapshot=JSON.parse(c.lastLevelSnapshot) as Character;snapshot.id=c.id;snapshot.ownerId=c.ownerId;snapshot.isDemo=false;c.lastLevelSnapshot=JSON.stringify(snapshot)}if(await persist(withHistory(c,'Importado desde JSON.'))){notify('Personaje importado.');navigate('library')}}catch(e){notify(e instanceof Error?e.message:'Archivo no válido.',true)}finally{if(importInput.current)importInput.current.value=''}};
  if(loadError)return <div className="loading"><Logo/><div className="error-box">{loadError}</div><Button onClick={()=>window.location.reload()}>Volver a intentar</Button></div>;
  if(!catalog)return <div className="loading"><Logo/><div className="loading-line"/><p>Abriendo tu grimorio…</p></div>;
  const currentDerived=active?deriveCharacter(active,catalog):null;
  const searchItems:Entity[]=active&&view==='sheet'?[...currentDerived!.features,...catalog.spells.filter(s=>Object.values(active.spellSelections).some(x=>x.known.includes(s.id))),...catalog.feats.filter(f=>active.featIds.includes(f.id)),...active.inventory.map(x=>({...x,source:{page:0},description:x.description+'\n'+x.notes})),...active.notes.map(n=>({id:n.id,name:n.title,description:n.content,source:{page:0}}))]:[...catalog.races,...catalog.classes,...catalog.feats,...catalog.spells,...catalog.backgrounds,...catalog.equipment];
  const results=globalQuery.trim()?searchItems.filter(i=>(i.name+' '+i.description).toLocaleLowerCase('es').includes(globalQuery.toLocaleLowerCase('es'))).slice(0,30):[];
  const title=view==='library'?'Mis personajes':view==='wizard'?'Crear personaje':view==='sheet'?(active?.name||'Personaje'):view==='source'?'Acerca de la fuente':reference;
  return <>
    {mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}
    <aside id="app-navigation" className={`sidebar ${mobile?'open':''}`}><Logo/>
      {view==='sheet'&&active?<><button className="nav-button" onClick={()=>navigate('library')}><ArrowLeft size={17}/>Todos los personajes</button><div className="nav-label">TU PERSONAJE</div>{SHEET_SECTIONS.map(n=><button key={n.id} className={`nav-button ${section===n.id?'active':''}`} onClick={()=>{setSection(n.id);setMobile(false)}}><n.icon size={17}/>{n.id}</button>)}</>:<><div className="nav-label">TU AVENTURA</div><button className={`nav-button ${view==='library'||view==='wizard'?'active':''}`} onClick={()=>navigate('library')}><FolderHeart size={17}/>Mis personajes<span className="nav-count">{characters.length}</span></button><div className="nav-label">EL COMPENDIO</div>{REFERENCE_SECTIONS.map(n=><button key={n.id} className={`nav-button ${view==='catalog'&&reference===n.id?'active':''}`} onClick={()=>{setReference(n.id);navigate('catalog')}}><n.icon size={17}/>{n.id}</button>)}</>}
      <div className="sidebar-bottom"><button className="nav-button" style={{padding:'9px 0',marginBottom:15}} onClick={()=>navigate('source')}><BookOpen size={16}/>Acerca de la fuente</button><div className="source-mini"><ScrollText size={19}/><span>Manual para Casi Todo<br/><small>D&D 5e · Edición 30.03.25</small></span></div><div className="local-status"><i/>Almacenamiento en este dispositivo</div></div>
    </aside>
    <div className="app-main"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Abrir menú" aria-controls="app-navigation" aria-expanded={mobile} onClick={()=>setMobile(true)}><Menu size={21}/></button><div className="breadcrumbs"><BookOpen size={14}/><span>Grimorio</span><ChevronRight size={12}/><strong>{title}</strong></div><div className="topbar-right"><button className="top-search" onClick={()=>setSearchOpen(true)} aria-label="Búsqueda global"><Search size={16}/><span>Buscar en {view==='sheet'?'el personaje':'el compendio'}</span><kbd className="shortcut">⌘ K</kbd></button><span className="local-status" style={{margin:0,color:saved==='error'?'#a84339':undefined}}>{saved==='saving'?<LoaderCircle size={12}/>:saved==='error'?<X size={12}/>:<Check size={12}/>}<span>{saved==='saving'?'Guardando…':saved==='error'?'Error al guardar':'Guardado'}</span></span><span className="user-avatar" title="Biblioteca local">AV</span></div></header>
      <main className="content">
      {view==='library'&&<Library characters={characters} catalog={catalog} onCreate={begin} onOpen={open} onDuplicate={duplicate} onDelete={setDeleteId} onExport={exportOne} onImport={()=>importInput.current?.click()} onReference={()=>{setReference('Razas y linajes');navigate('catalog')}}/>}
      {view==='wizard'&&draft&&<CharacterWizard initial={draft} catalog={catalog} onCancel={()=>navigate('library')} onDraft={setDraft} onCreate={async c=>{if(await persist(c)){setDraft(null);open(c);notify('Tu personaje está listo para la aventura.')}}}/>}
      {view==='sheet'&&active&&<CharacterSheet character={active} catalog={catalog} section={section} onSection={setSection} onChange={persist} onExport={()=>exportOne(active)} onNotify={notify} onDetail={setDetail}/>}
      {view==='catalog'&&<CatalogView catalog={catalog} category={reference} onDetail={setDetail}/>}
      {view==='source'&&<SourceView catalog={catalog}/>}
      </main>
    </div>
    <input ref={importInput} type="file" accept="application/json,.json" hidden onChange={e=>void importFile(e.target.files?.[0])}/>
    <Modal open={!!deleteId} onClose={()=>setDeleteId('')} title="Eliminar personaje" description="Esta acción elimina el personaje de este navegador. Puedes exportar una copia antes de continuar."><p>¿Eliminar a <strong>{characters.find(c=>c.id===deleteId)?.name}</strong>?</p><div className="modal-footer"><Button onClick={()=>setDeleteId('')}>Cancelar</Button><Button variant="danger" onClick={async()=>{try{await repo.current!.delete(deleteId);setCharacters(cs=>cs.filter(c=>c.id!==deleteId));setDeleteId('');notify('Personaje eliminado.')}catch(e){notify(String(e),true)}}}><Trash2 size={15}/>Eliminar personaje</Button></div></Modal>
    <Modal open={searchOpen} onClose={()=>setSearchOpen(false)} title={view==='sheet'?'Buscar en tu personaje':'Buscar en el compendio'} wide><div className="search-field"><Search size={17}/><input autoFocus placeholder="Rasgos, hechizos, dotes, objetos, notas…" value={globalQuery} onChange={e=>setGlobalQuery(e.target.value)}/></div><div className="stack" style={{marginTop:18,gap:8}}>{results.map(item=><button key={item.id} className="check-option" onClick={()=>{setSearchOpen(false);setDetail(item)}}><BookOpen size={17}/><span><strong>{item.name}</strong><small>{cleanDescription(item.description,110)}</small></span></button>)}{globalQuery&&!results.length&&<Empty title="No hay coincidencias" description="Prueba con otro nombre o fragmento de texto."/>}{!globalQuery&&<p className="subtle">Escribe para buscar entre {searchItems.length} entradas.</p>}</div></Modal>
    <Modal open={!!detail} onClose={()=>setDetail(null)} title={detail?.name||''} wide>{detail&&<><SourceTag source={detail.source.page?detail.source:undefined}/><p className="source-prose">{detail.description}</p>{detail.automationNotes?.map((n,i)=><div key={i} className="info-box" style={{marginTop:18}}>{n}</div>)}</>}</Modal>
    {toast&&<div className={`toast ${toast.error?'error':''}`} role={toast.error?'alert':'status'}>{toast.error?<CircleHelp size={17}/>:<Check size={17}/>} {toast.text}<button className="icon-button" onClick={()=>setToast(null)} aria-label="Cerrar aviso"><X size={15}/></button></div>}
  </>
}

function Library({characters,catalog,onCreate,onOpen,onDuplicate,onDelete,onExport,onImport,onReference}:{characters:Character[];catalog:Catalog;onCreate:()=>void;onOpen:(c:Character)=>void;onDuplicate:(c:Character)=>void;onDelete:(id:string)=>void;onExport:(c:Character)=>void;onImport:()=>void;onReference:()=>void}){
  const [query,setQuery]=useState(''),[sort,setSort]=useState('recent'),[layout,setLayout]=useState('grid'),[menu,setMenu]=useState('');
  const list=characters.filter(c=>[c.name,c.concept,catalog.races.find(r=>r.id===c.raceId)?.name,...c.classes.map(x=>catalog.classes.find(cl=>cl.id===x.classId)?.name)].join(' ').toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'es'):sort==='level'?b.classes.reduce((s,c)=>s+c.level,0)-a.classes.reduce((s,c)=>s+c.level,0):b.updatedAt.localeCompare(a.updatedAt));
  return <><section className="library-hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={13}/>TUS PERSONAJES. TUS HISTORIAS.</div><h1>Hay una leyenda<br/>esperando a ser escrita.</h1><p>Reúne a tus héroes, prepara tu próxima aventura<br className="desktop-only"/> y deja que los dados cuenten el resto.</p></div><div className="hero-mark"><Logo small/>EL COMIENZO DE ALGO EXTRAORDINARIO</div></section>
    <div className="page-heading between"><div><h1>Mis personajes</h1><p>{characters.length} {characters.length===1?'historia en tu colección':'historias en tu colección'} · Infinitas aventuras por delante</p></div><div className="flex"><Button onClick={onImport}><Upload size={15}/>Importar</Button><Button variant="primary" onClick={onCreate}><Plus size={17}/>Crear personaje</Button></div></div>
    <div className="library-tools"><div className="search-field"><Search size={17}/><input aria-label="Buscar personajes" placeholder="Buscar por nombre, raza o clase…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Ordenar personajes"><option value="recent">Última modificación</option><option value="name">Nombre: A–Z</option><option value="level">Nivel: mayor primero</option></select><div className="view-toggle"><button className={layout==='grid'?'active':''} aria-label="Vista de tarjetas" onClick={()=>setLayout('grid')}><LayoutGrid size={15}/></button><button className={layout==='list'?'active':''} aria-label="Vista de lista" onClick={()=>setLayout('list')}><List size={17}/></button></div></div>
    <div className={`character-grid ${layout}`}>
      {list.map(c=>{const d=deriveCharacter(c,catalog),cl=catalog.classes.find(x=>x.id===c.classes[0]?.classId),sub=cl?.subclasses.find(x=>x.id===c.classes[0]?.subclassId),race=catalog.races.find(r=>r.id===(c.subraceId||c.raceId));return <article className="character-card" key={c.id}>
        <div className="card-portrait" onClick={()=>onOpen(c)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onOpen(c)}}} aria-label={`Abrir ${c.name}`}>{c.portrait?<img src={c.portrait} alt={c.name}/>:<div className="portrait-placeholder" style={{backgroundColor:c.color}}><ClassIcon id={cl?.id} size={62}/></div>}{c.isDemo&&<span className="demo-badge">PERSONAJE DEMO</span>}<span className="level-badge">NIVEL {d.level}</span><div className="portrait-title"><h3>{c.name}</h3><p>{race?.name||'Origen por definir'}</p></div></div>
        <div className="card-details"><div className="character-type"><ClassIcon id={cl?.id} size={16}/>{c.classes.map(x=>`${catalog.classes.find(y=>y.id===x.classId)?.name||x.classId}${c.classes.length>1?' '+x.level:''}`).join(' / ')}{sub&&<span className="subtle" style={{fontSize:10,marginLeft:'auto',maxWidth:'58%',textAlign:'right'}}>{sub.name}</span>}</div><div className="card-stats"><div><span>CLASE DE ARMADURA</span><strong><Shield size={13}/>{d.ac.value}</strong></div><div><span>PUNTOS DE GOLPE</span><strong>{c.hp.current}<small> / {d.hpMax.value}</small></strong></div><div><span>COMPETENCIA</span><strong>+{d.proficiency.value}</strong></div></div><div className="card-footer"><button className="card-open" onClick={()=>onOpen(c)}>Abrir personaje<ArrowRight size={14}/></button><button className="icon-button" aria-label={`Opciones de ${c.name}`} aria-expanded={menu===c.id} onClick={()=>setMenu(menu===c.id?'':c.id)}><MoreHorizontal size={19}/></button></div></div>
        {menu===c.id&&<div className="card-menu"><button onClick={()=>{setMenu('');onOpen(c)}}><Feather size={14}/>Editar personaje</button><button onClick={()=>{setMenu('');onDuplicate(c)}}><Copy size={14}/>Duplicar</button><button onClick={()=>{setMenu('');onExport(c)}}><Download size={14}/>Exportar JSON</button><button onClick={()=>{setMenu('');onDelete(c.id)}} style={{color:'var(--red)'}}><Trash2 size={14}/>Eliminar</button></div>}
      </article>})}
      <button className="new-character-card" onClick={onCreate}><span><Plus size={25} strokeWidth={1.3}/></span><h3>Una nueva historia</h3><p>Crea un personaje paso a paso.<br/>La aventura empieza contigo.</p></button>
    </div>
    {query&&!list.length&&<Empty title="No encontramos ese personaje" description="Prueba a buscar por su clase o su raza."/>}
    <p className="library-footnote"><Save size={12}/>Tus personajes se guardan automáticamente en este navegador. Exporta una copia para llevarlos contigo.</p>
    <div className="quick-guide"><span className="guide-icon"><BookOpen size={22} strokeWidth={1.4}/></span><div><h3>Todo un mundo de posibilidades</h3><p>Explora las razas, clases, dotes y hechizos del Manual para Casi Todo.</p></div><Button variant="ghost" onClick={onReference}>Explorar el compendio<ArrowRight size={14}/></Button></div>
  </>
}

function SourceView({catalog}:{catalog:Catalog}){return <div className="stack"><div className="page-heading"><span className="eyebrow">LA BIBLIOTECA DE REGLAS</span><h1 style={{marginTop:12}}>Una fuente. Cada referencia.</h1><p>Manual para Casi Todo de D&D 5e · Versión 30.03.25</p></div><div className="source-stats">{[[633,'Páginas analizadas'],[catalog.races.length,'Razas, linajes y variantes'],[catalog.classes.length,'Clases'],[catalog.classes.reduce((n,c)=>n+c.subclasses.length,0),'Subclases'],[catalog.spells.length,'Hechizos'],[catalog.feats.length,'Dotes'],[catalog.backgrounds.length,'Trasfondos'],[catalog.equipment.length,'Entradas de equipo']].map(([value,name])=><div className="source-stat" key={name}><strong>{value}</strong><span>{name}</span></div>)}</div><div className="panel"><h2>Del manual a tu personaje</h2><p className="source-prose">Cada entrada conserva su descripción y la página física del PDF. Las versiones originales, Legado y Multiverso se mantienen separadas. Los valores derivados muestran sus componentes y permiten una sustitución manual reversible.</p><div className="divider"/><h3>Lo que necesita tu criterio</h3><p className="source-prose">Los efectos contextuales, las decisiones narrativas y las opciones que aún no tienen una regla estructurada deben revisarse en su descripción. El catálogo completo no equivale a automatización completa de cada interacción.</p><p className="source-prose">La fuente no proporciona el procedimiento completo de compra de puntos, la matriz estándar, las reglas generales de descanso ni una tabla de experiencia. Las puntuaciones se introducen manualmente, la subida de nivel se inicia por decisión del jugador y los descansos recuperan únicamente recursos con una regla explícita.</p><div className="info-box" style={{marginTop:20}}>Las discrepancias del propio manual se conservan. Un conjuro con nivel contradictorio queda fuera de la selección automática. Las ampliaciones opcionales de Tasha requieren activación explícita.</div></div><div className="panel"><h3>Tus datos son tuyos</h3><p className="source-prose">Los personajes se guardan en este navegador y dispositivo. Puedes exportarlos a JSON, importarlos en otra instalación e imprimir su ficha. No necesitas cuenta ni conexión con un servicio externo para guardar.</p></div></div>}
