'use client';
import * as Dialog from '@radix-ui/react-dialog';
import { X, Check, ChevronDown, BookOpen, Info, Sparkles, Shield, Swords, WandSparkles, Leaf, Music, Flame, Crosshair, Heart, Hand, Hexagon, Wrench, Sword, Zap } from 'lucide-react';
import type { ReactNode } from 'react';
import type { DerivedValue, Entity, Source } from '@/lib/types';

export function Logo({small=false}:{small?:boolean}) {return <div className={`brand ${small?'small':''}`}><svg viewBox="0 0 40 44" aria-hidden="true"><path d="M20 2 37 12v20L20 42 3 32V12Z M20 2 10 28h20ZM3 12h34M3 32l7-4 10 14 10-14 7 4M20 2v10M10 28l-7-16M30 28l7-16" fill="none" stroke="currentColor" strokeWidth="1.25"/></svg>{!small&&<span>GRIMORIO<small>EL ARTE DE LA AVENTURA</small></span>}</div>}
export function ClassIcon({id,size=24}:{id?:string;size?:number}) { const Icon = id?.includes('artificiero')?Wrench:id?.includes('picaro')?Sword:id?.includes('hechicero')?Zap:id?.includes('mago')?WandSparkles:id?.includes('guerrero')?Swords:id?.includes('paladin')?Shield:id?.includes('druida')?Leaf:id?.includes('bardo')?Music:id?.includes('barbaro')?Flame:id?.includes('explorador')?Crosshair:id?.includes('clerigo')?Heart:id?.includes('monje')?Hand:id?.includes('brujo')?Hexagon:Sparkles;return <Icon size={size}/> }
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;wide?:boolean}) {return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${wide?'modal-wide':''}`} aria-describedby={description?'dialog-description':undefined}><header className="modal-header"><div><span className="eyebrow">GRIMORIO PERSONAL</span><Dialog.Title>{title}</Dialog.Title>{description&&<Dialog.Description id="dialog-description">{description}</Dialog.Description>}</div><Dialog.Close className="icon-button" aria-label="Cerrar"><X size={20}/></Dialog.Close></header>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Button({children,variant='secondary',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}) {return <button className={`button ${variant} ${className}`} {...props}>{children}</button>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}) {return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function SourceTag({source}:{source?:Source}) {return source?<span className="source-tag" title={source.title}><BookOpen size={12}/> {source.book||'Manual'}{source.page>0?` · p. ${source.page}`:''}{source.endPage&&source.endPage!==source.page?`–${source.endPage}`:''}</span>:null}
export function Empty({icon, title,description,children}:{icon?:ReactNode;title:string;description?:string;children?:ReactNode}) {return <div className="empty-state"><div className="empty-icon">{icon||<BookOpen size={28}/>}</div><h3>{title}</h3>{description&&<p>{description}</p>}{children}</div>}
export function Stat({label,value,suffix,derived,onClick,icon}:{label:string;value:string|number;suffix?:string;derived?:DerivedValue;onClick?:()=>void;icon?:ReactNode}) {return <button className={`stat ${derived?.mode==='override'?'overridden':''}`} onClick={onClick} type="button"><span className="stat-label">{icon}{label}{derived?.mode==='override'&&<i>OVERRIDE</i>}</span><strong>{value}<small>{suffix}</small></strong>{derived&&<span className="stat-foot"><Info size={11}/>{derived.mode==='manual'?'Valor manual':'Ver cálculo'}</span>}</button>}
export function DetailCard({item,children,meta}:{item:Entity;children?:ReactNode;meta?:ReactNode}) {return <details className="detail-card"><summary><span><strong>{item.name}</strong>{meta}</span><ChevronDown size={17}/></summary><div className="detail-body"><SourceTag source={item.source}/><p className="source-prose">{item.description}</p>{children}</div></details>}
export function CheckOption({selected,onClick,title,description,disabled=false}:{selected:boolean;onClick:()=>void;title:string;description?:string;disabled?:boolean}) {return <button type="button" className={`check-option ${selected?'selected':''}`} onClick={onClick} disabled={disabled} aria-pressed={selected}><span className="checkbox">{selected&&<Check size={14}/>}</span><span><strong>{title}</strong>{description&&<small>{description}</small>}</span></button>}
export function sign(n:number){return n>=0?`+${n}`:String(n)}
export function cleanDescription(s:string,max=180){const t=s.replace(/\s+/g,' ').trim();return t.length>max?t.slice(0,max).replace(/\s\S*$/,'')+'…':t}
export function downloadText(text:string,filename:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
