'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronRight, Dice5, Feather, Info, Search, Shield, Sparkles, WandSparkles, BookOpen, Plus, Minus } from 'lucide-react';
import type { Ability, Catalog, Character, Choice, ChoiceOption, Entity, Spell } from '@/lib/types';
import { deriveCharacter, getAllChoices, getClassGrantedSpells, getFixedClassCantrips, eligibleExpertiseOptions, checkPrerequisites, validateCharacter, validSpells, spellbookMinimum, withHistory } from '@/lib/engine';
import { ABILITIES, SKILLS, STANDARD_LANGUAGES_2014, EXOTIC_LANGUAGES_2014 } from '@/lib/constants';
import { Button, CheckOption, ClassIcon, Empty, Field, Modal, SourceTag, cleanDescription, sign } from './ui';
import { RaceDetails, SpellDetails } from './reference';
import { EquipmentPicker } from './equipment-picker';
import { StartingEquipment, StartingEquipmentSummary } from './starting-equipment';
import { applyStartingEquipment, startingEquipmentIssues } from '@/lib/equipment';
import { AbilityGeneration } from './ability-generation';
import { abilityGenerationIssues } from '@/lib/ability-generation';

const STEPS=['Concepto','Origen','Clase','Características','Competencias','Opciones','Hechizos','Identidad','Equipo','Revisión'];
type EditorProps={character:Character;catalog:Catalog;onChange:(c:Character)=>void};

export function CharacterWizard({initial,initialStep,catalog,onCreate,onCancel,onDraft}:{initial:Character;initialStep:number;catalog:Catalog;onCreate:(c:Character)=>void;onCancel:()=>void;onDraft:(c:Character,step:number)=>void}){
  const [c,setC]=useState(initial),[step,setStep]=useState(initialStep),[query,setQuery]=useState(''),[version,setVersion]=useState('Todas'),[detail,setDetail]=useState<Entity|null>(null),[errors,setErrors]=useState<string[]>([]),[manualReviewed,setManualReviewed]=useState(false);
  const update=(next:Character)=>{setC(next);onDraft(next,step);setErrors([])};
  const d=deriveCharacter(c,catalog),race=catalog.races.find(r=>r.id===c.raceId),subrace=catalog.races.find(r=>r.id===c.subraceId),cls=catalog.classes.find(x=>x.id===c.classes[0]?.classId),choices=getAllChoices(c,catalog);
  const subraces=catalog.races.filter(r=>r.parentId===c.raceId),rootRaces=catalog.races.filter(r=>!r.parentId),shownRaces=rootRaces.filter(r=>(version==='Todas'||r.version===version)&&r.name.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
  const skillChoices=choices.filter(ch=>['skills','choose_skill','choose_proficiency','choose_tool','choose_language'].includes(ch.type));
  const otherChoices=choices.filter(ch=>!skillChoices.some(x=>x.id===ch.id));
  const next=()=>{const issues=step===0&&!c.name.trim()?['Escribe un nombre para tu personaje.']:step===1&&!c.raceId?['Selecciona una raza o linaje.']:step===2&&!c.classes.length?['Selecciona una clase.']:step===3?abilityGenerationIssues(c):step===8?startingEquipmentIssues(c,catalog):[];if(issues.length){setErrors(issues);return}const nextStep=Math.min(9,step+1);setStep(nextStep);onDraft(c,nextStep);setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
  const finish=()=>{const issues=[...validateCharacter(c,catalog),...abilityGenerationIssues(c),...startingEquipmentIssues(c,catalog)];if(issues.length){setErrors(issues);return}if(!manualReviewed){setErrors(['Confirma que has revisado los rasgos y las decisiones que requieren gestión manual.']);return}const ready=applyStartingEquipment(structuredClone(c),catalog);ready.hp.current=d.hpMax.value;onCreate(withHistory(ready,'Personaje creado.'))};
  return <><div className="wizard-heading"><div className="between"><span className="eyebrow">UNA NUEVA HISTORIA</span><Button variant="ghost" className="compact" onClick={onCancel}><ArrowLeft size={14}/>Volver a la biblioteca</Button></div><h1>Da vida a tu personaje</h1><p className="subtle">Tus cambios se guardan como borrador en este navegador.</p></div><div className="wizard-progress" aria-label={`Paso ${step+1} de 10`}>{STEPS.map((_,i)=><span key={i} className={i<=step?'done':''}/>)}</div><div className="wizard-steps">{STEPS.map((name,i)=><button key={name} className={i===step?'active':''} onClick={()=>{setStep(i);onDraft(c,i);setErrors([]);setQuery('')}}><i>{i<step?<Check size={11}/>:i+1}</i>{name}</button>)}</div>
    <div className="wizard-layout"><section className="wizard-main">
      {step===0&&<><h2>Antes de los dados, una idea</h2><p>El nombre y el concepto se pueden cambiar en cualquier momento.</p><div className="panel stack"><Field label="Nombre del personaje"><input autoFocus placeholder="¿Cómo se llama tu héroe?" value={c.name} maxLength={120} onChange={e=>update({...c,name:e.target.value})}/></Field><Field label="Concepto"><textarea placeholder="Una cartógrafa en busca de una ciudad perdida, un guerrero que ha hecho una promesa…" value={c.concept} onChange={e=>update({...c,concept:e.target.value})}/></Field><Field label="Trasfondo (opcional)"><select value={c.backgroundId} onChange={e=>update({...c,backgroundId:e.target.value})}><option value="">Elegir más adelante</option>{catalog.backgrounds.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>{c.backgroundId&&<><Button variant="ghost" onClick={()=>setDetail(catalog.backgrounds.find(x=>x.id===c.backgroundId)!)}><BookOpen size={15}/>Ver descripción completa</Button><p className="subtle">Revisa el equipo, los idiomas y las decisiones del trasfondo.</p></>}</div></>}
      {step===1&&<><h2>¿De dónde vienes?</h2><p>Cada versión conserva sus propios rasgos. Elige la que usaréis en tu mesa.</p><div className="library-tools"><div className="search-field"><Search size={17}/><input placeholder="Buscar raza o linaje…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={version} onChange={e=>setVersion(e.target.value)} aria-label="Versión racial"><option>Todas</option>{Array.from(new Set(rootRaces.map(r=>r.version))).map(v=><option key={v}>{v}</option>)}</select></div><div className="option-grid" style={{maxHeight:440,overflowY:'auto',padding:2}}>{shownRaces.map(r=><button key={r.id} className={`option-card ${r.id===c.raceId?'selected':''}`} onClick={()=>update({...c,raceId:r.id,subraceId:''})}><div className="between" style={{width:'100%'}}><h3>{r.name}</h3>{r.id===c.raceId&&<Check size={17}/>}</div><span className="badge">{r.version}</span><p>{Object.entries(r.abilityBonuses).map(([id,v])=>`+${v} ${ABILITIES.find(a=>a.id===id)?.short}`).join(' · ')||'Aumentos a elección o según rasgo'}{r.speed?` · ${r.speed} pies`:''}</p><SourceTag source={r.source}/></button>)}</div>{race&&<div className="selection-summary"><div className="between"><h3>{race.name}</h3><Button className="compact" variant="ghost" onClick={()=>setDetail(race)}>Ver descripción completa<Info size={14}/></Button></div><p className="subtle">{race.size||'Tamaño según descripción'} · {race.speed?`${race.speed} pies`:'Velocidad según linaje'} · {race.languages.join(', ')||'Idiomas según elección'}</p>{race.senses.length>0&&<p className="subtle">{race.senses.join(' · ')}</p>}{race.resistances.length>0&&<p className="subtle">Resistencias: {race.resistances.join(', ')}</p>}{subraces.length>0&&<Field label="Subraza o variante"><select value={c.subraceId} onChange={e=>update({...c,subraceId:e.target.value})}><option value="">Seleccionar…</option>{subraces.map(r=><option key={r.id} value={r.id}>{r.name} · {r.version}</option>)}</select></Field>}{subrace&&<Button variant="ghost" className="compact" onClick={()=>setDetail(subrace)}>Ver rasgos de {subrace.name}</Button>}</div>}</>}
      {step===2&&<><h2>Tu manera de vivir la aventura</h2><p>Empiezas en nivel 1. La subclase se elegirá en el nivel que indique tu clase.</p><div className="option-grid">{catalog.classes.map(cl=><button key={cl.id} className={`option-card ${cl.id===cls?.id?'selected':''}`} onClick={()=>update({...c,classes:[{classId:cl.id,level:1}],hp:{...c.hp,rolls:[]},spellSelections:{}})}><div className="class-symbol" style={{width:'100%'}}><ClassIcon id={cl.id} size={26}/>{cl.id===cls?.id&&<Check size={17}/>}</div><h3>{cl.name}</h3><p>Dado de golpe d{cl.hitDie||'?'} · {cl.primaryAbilities.map(a=>ABILITIES.find(x=>x.id===a)?.label||a).join(', ')}</p><SourceTag source={cl.source}/></button>)}</div>{cls&&<div className="selection-summary"><div className="between"><h3>{cls.name}</h3><Button variant="ghost" className="compact" onClick={()=>setDetail(cls)}>Ver descripción completa</Button></div><p className="subtle">Subclase en nivel {cls.subclassLevel||'según descripción'} · {cls.skillChoices.amount} habilidades a elección</p><p className="subtle">Salvaciones: {cls.savingThrows.map(a=>ABILITIES.find(x=>x.id===a)?.label||a).join(', ')}</p></div>}</>}
      {step===3&&<><h2>Las seis caras de tu héroe</h2><p>Elige el método de D&D 2014 acordado con tu mesa.</p><AbilityGeneration character={c} catalog={catalog} onChange={update}/></>}
      {step===4&&<><h2>Tu experiencia marca la diferencia</h2><p>Selecciona las competencias e idiomas que corresponden a tu origen y clase.</p><ChoicesEditor character={c} catalog={catalog} onChange={update} choices={skillChoices}/>{!skillChoices.length&&<Empty title="Sin elecciones de competencia" description="Selecciona primero un origen y una clase."/>}</>}
      {step===5&&<><h2>Los detalles que te hacen único</h2><p>Estas elecciones proceden de los rasgos activos de tu personaje.</p><ChoicesEditor character={c} catalog={catalog} onChange={update} choices={otherChoices}/>{!otherChoices.length&&<Empty icon={<Check size={28}/>} title="Todo en orden" description="En este nivel no hay más elecciones estructuradas. Revisa los rasgos al finalizar."/>}</>}
      {step===6&&<><h2>Las primeras páginas de tu grimorio</h2><p>Solo aparecen hechizos válidos para tus clases y sus niveles.</p><SpellPicker character={c} catalog={catalog} onChange={update}/></>}
      {step===7&&<><h2>Mucho más que una ficha</h2><p>Un rostro, una promesa, algo por lo que luchar. Puedes completarlo después.</p><IdentityEditor character={c} catalog={catalog} onChange={update}/></>}
      {step===8&&<><h2>Prepara el camino</h2><p>Elige el equipo de tu clase y trasfondo, o su alternativa de oro inicial.</p><StartingEquipment character={c} catalog={catalog} onChange={update}/><div className="panel stack" style={{marginTop:24}}><h3>Equipo adicional</h3><p className="subtle">Añade compras y objetos acordados con tu mesa. Indica su cantidad después de buscarlos.</p><EquipmentPicker character={c} catalog={catalog} onChange={update} allowHomebrew/></div></>}
      {step===9&&<><h2>Todo listo para la aventura</h2><p>Revisa tus decisiones antes de escribir la primera página.</p><div className="panel"><h2>{c.name||'Sin nombre'}</h2><p className="subtle" style={{marginTop:10}}>{c.concept}</p><dl className="review-list">{[['Origen',subrace?.name||race?.name||'Pendiente'],['Clase',cls?.name||'Pendiente'],['Nivel','1'],['Puntos de golpe',String(d.hpMax.value)],['Competencia',sign(d.proficiency.value)],['Hechizos',String(Object.values(c.spellSelections).reduce((n,s)=>n+s.known.length,0))]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><div className="divider"/><div className="grid-3">{ABILITIES.map(a=><div key={a.id}><span className="eyebrow">{a.short}</span><h3>{d.abilities[a.id].total} <small>({sign(d.abilities[a.id].modifier)})</small></h3></div>)}</div></div><StartingEquipmentSummary character={c} catalog={catalog}/><div className="selection-summary"><h3>Rasgos de nivel 1</h3><div className="flex wrap" style={{marginTop:12}}>{d.features.map(f=><button key={f.id} className="badge" onClick={()=>setDetail(f)}>{f.name}</button>)}</div></div>{d.warnings.length>0&&<div className="info-box" style={{marginTop:18}}>{d.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}<div style={{marginTop:18}}><CheckOption selected={manualReviewed} onClick={()=>setManualReviewed(v=>!v)} title="He revisado los rasgos de mi personaje" description="Las opciones contextuales o sin selector se gestionan manualmente desde la ficha, conservando su descripción original."/></div></>}
      {errors.length>0&&<div className="error-box" role="alert" style={{marginTop:20}}><strong>Quedan decisiones por resolver</strong><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}
      <div className="wizard-footer"><Button variant="ghost" onClick={()=>{if(step===0)onCancel();else{setStep(step-1);onDraft(c,step-1);setErrors([])}}}><ArrowLeft size={15}/>{step===0?'Volver':'Anterior'}</Button><span className="subtle">{step+1} de 10</span>{step<9?<Button variant="primary" onClick={next}>Continuar<ArrowRight size={15}/></Button>:<Button variant="primary" onClick={finish}><Sparkles size={16}/>Crear personaje</Button>}</div>
    </section><aside className="wizard-preview"><span className="eyebrow">TU PERSONAJE</span><div className="preview-icon"><ClassIcon id={cls?.id} size={32}/></div><h3>{c.name||'Una nueva leyenda'}</h3><p>{subrace?.name||race?.name||'Un origen por descubrir'}</p><dl><div><dt>Clase</dt><dd>{cls?.name||'—'}</dd></div><div><dt>Nivel</dt><dd>1</dd></div><div><dt>Puntos de golpe</dt><dd>{cls?d.hpMax.value:'—'}</dd></div><div><dt>Competencia</dt><dd>{cls?sign(d.proficiency.value):'—'}</dd></div><div><dt>Velocidad</dt><dd>{race?`${d.speed.value} pies`:'—'}</dd></div></dl></aside></div>
    <Modal open={!!detail} onClose={()=>setDetail(null)} title={detail?.name||''} wide>{detail&&(catalog.races.some(r=>r.id===detail!.id)?<RaceDetails race={catalog.races.find(r=>r.id===detail!.id)!} catalog={catalog}/>:<><SourceTag source={detail.source}/><p className="source-prose">{detail.description}</p></>)}</Modal>
  </>
}

export function AbilityEditor({character:c,catalog,onChange}:EditorProps){const d=deriveCharacter(c,catalog);return <div className="ability-grid">{ABILITIES.map(a=><div className="ability-editor" key={a.id}><h3>{a.label}</h3><label><span className="subtle">Puntuación base</span><input aria-label={`${a.label} base`} type="number" min="1" max="20" value={c.abilities[a.id]} onChange={e=>onChange({...c,abilities:{...c.abilities,[a.id]:Number(e.target.value)}})}/></label><small>Bonificadores {sign(d.abilities[a.id].bonus)}</small><div className="ability-total">{d.abilities[a.id].total} <small style={{display:'inline',fontSize:15}}>({sign(d.abilities[a.id].modifier)})</small></div><small>Puntuación total · modificador</small></div>)}</div>}

function LanguageChoice({choice,selected,character,catalog,onSelect}:{choice:Choice;selected:string[];character:Character;catalog:Catalog;onSelect:(values:string[])=>void}){
  const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es').trim();
  const before={...character,choices:{...character.choices,[choice.id]:[]}};
  const knownLanguages=deriveCharacter(before,catalog).languages;
  const known=new Set(knownLanguages.map(normalize));
  const picked=selected.filter(Boolean).slice(0,choice.amount);
  const listedLanguages=[...STANDARD_LANGUAGES_2014,...EXOTIC_LANGUAGES_2014];
  const otherLanguages=[...new Set([...catalog.races,...catalog.backgrounds].flatMap(origin=>origin.languages??[]))].filter(language=>!listedLanguages.some(listed=>normalize(listed)===normalize(language))).sort((a,b)=>a.localeCompare(b,'es'));
  return <div className="choice-group"><div className="choice-title"><h3>{choice.name}</h3><span className="badge">{picked.length} / {choice.amount}</span></div>{choice.source&&<SourceTag source={choice.source}/>}<p className="subtle" style={{margin:'10px 0 14px'}}>Elige un idioma que tu personaje aún no conozca. Los idiomas exóticos requieren el acuerdo del DM.</p><div className="known-languages"><strong>Idiomas que ya conoces</strong><div className="flex wrap">{knownLanguages.length?knownLanguages.map(language=><span className="badge" key={language}>{language}</span>):<span className="subtle">Ninguno todavía</span>}</div></div><div className="grid-2">{Array.from({length:choice.amount},(_,index)=>{const current=picked[index]??'',taken=new Set(picked.filter((_,i)=>i!==index).map(normalize));const options=(list:string[])=>list.filter(language=>!known.has(normalize(language))&&!taken.has(normalize(language)));const listed=[...listedLanguages,...otherLanguages].some(language=>normalize(language)===normalize(current));return <Field label={`Idioma ${index+1}`} key={index}><select aria-label={`Idioma ${index+1} de ${choice.name}`} value={current} disabled={index>picked.length} onChange={e=>{const next=[...picked];next[index]=e.target.value;onSelect(next.filter(Boolean))}}><option value="">Seleccionar idioma…</option>{current&&(known.has(normalize(current))||!listed)&&<option value={current} disabled>{current}{known.has(normalize(current))?' · ya conocido':' · idioma guardado'}</option>}<optgroup label="Idiomas comunes">{options(STANDARD_LANGUAGES_2014).map(language=><option key={language} value={language}>{language}</option>)}</optgroup><optgroup label="Idiomas exóticos · consultar con el DM">{options(EXOTIC_LANGUAGES_2014).map(language=><option key={language} value={language}>{language}</option>)}</optgroup>{otherLanguages.length>0&&<optgroup label="Otros idiomas del catálogo · consultar con el DM">{options(otherLanguages).map(language=><option key={language} value={language}>{language}</option>)}</optgroup>}</select></Field>})}</div></div>;
}

function AbilityIncreaseChoice({choice,selected,onSelect}:{choice:Choice;selected:string[];onSelect:(values:string[])=>void}){
  const options=choice.options.filter((option):option is ChoiceOption=>typeof option!=='string'&&!!option.effects?.length&&option.effects.every(effect=>effect.type==='ability_bonus'&&effect.ability&&typeof effect.value==='number'));
  const patternOf=(option:ChoiceOption)=>option.effects!.map(effect=>Number(effect.value)).sort((a,b)=>b-a);
  const patterns=[...new Set(options.map(option=>patternOf(option).join(',')))];
  const selectedOption=options.find(option=>option.id===selected[0]);
  const [pattern,setPattern]=useState(selectedOption?patternOf(selectedOption).join(','):patterns[0]);
  const [draft,setDraft]=useState<(Ability|null)[]>(()=>{
    const effects=[...(selectedOption?.effects??[])];
    return (selectedOption?patternOf(selectedOption):patterns[0]?.split(',').map(Number)??[]).map(value=>{
      const index=effects.findIndex(effect=>effect.value===value);
      return index<0?null:effects.splice(index,1)[0].ability??null;
    });
  });
  const values=pattern.split(',').map(Number);
  const matches=(candidate:(Ability|null)[])=>options.some(option=>patternOf(option).join(',')===pattern&&candidate.every((ability,index)=>!ability||option.effects?.some(effect=>effect.ability===ability&&effect.value===values[index])));
  const choose=(index:number,ability:Ability)=>{
    const next=[...draft];next[index]=next[index]===ability?null:ability;setDraft(next);
    const complete=next.every(Boolean);
    const match=complete?options.find(option=>patternOf(option).join(',')===pattern&&next.every((id,i)=>option.effects?.some(effect=>effect.ability===id&&effect.value===values[i]))):undefined;
    onSelect(match?[match.id]:[]);
  };
  return <div className="choice-group ability-increase" key={choice.id}><div className="choice-title"><h3>{choice.name}</h3><span className="badge">{selectedOption?'Elegido':'Por elegir'}</span></div>{choice.source&&<SourceTag source={choice.source}/>}<p className="subtle">Reparte los aumentos entre las características permitidas.</p>{patterns.length>1&&<div className="ability-patterns" role="group" aria-label="Reparto de aumentos">{patterns.map(key=><button type="button" key={key} className={pattern===key?'active':''} aria-pressed={pattern===key} onClick={()=>{setPattern(key);setDraft(key.split(',').map(()=>null));onSelect([])}}>{key.split(',').map(value=>`+${value}`).join(' · ')}</button>)}</div>}<div className="ability-increase-slots">{values.map((value,index)=><div className="ability-increase-slot" key={`${pattern}-${index}`}><div className="ability-increase-slot-heading"><strong>+{value}</strong><span>{draft[index]?ABILITIES.find(a=>a.id===draft[index])?.label:`Elige una característica`}</span></div><div className="ability-increase-grid">{ABILITIES.map(ability=>{const candidate=[...draft];candidate[index]=ability.id;const available=(draft[index]===ability.id||!draft.includes(ability.id))&&matches(candidate);return <button type="button" key={ability.id} disabled={!available} className={draft[index]===ability.id?'selected':''} aria-pressed={draft[index]===ability.id} onClick={()=>choose(index,ability.id)}>{ability.label}</button>})}</div></div>)}</div>{selectedOption&&<p className="ability-increase-result"><Check size={15}/>{selectedOption.name}</p>}</div>;
}

export function ChoicesEditor({character:c,catalog,onChange,choices}:{choices:Choice[]}&EditorProps){const [detail,setDetail]=useState<Entity|null>(null),[filter,setFilter]=useState<Record<string,string>>({});
  const set=(choice:Choice,values:string[])=>{const next={...c,choices:{...c.choices,[choice.id]:values}};if(choice.type==='subclass'||choice.type==='choose_subclass'){next.classes=c.classes.map(cl=>cl.classId===choice.classId?{...cl,subclassId:values[0]||''}:cl)}onChange(next)};
  return <>{choices.map(choice=>{const selected=(choice.type==='subclass'||choice.type==='choose_subclass')?[c.classes.find(cl=>cl.classId===choice.classId)?.subclassId||'']:(c.choices[choice.id]||[]);let options:ChoiceOption[]=choice.options.map(o=>typeof o==='string'?{id:o,name:SKILLS.find(skill=>skill.id===o)?.name??o}:o);if(choice.type==='expertise'||options.some(option=>option.effects?.some(effect=>effect.type==='skill_expertise'))){const eligible=new Set(eligibleExpertiseOptions(c,choice,catalog));options=options.filter(option=>eligible.has(option.id)).map(option=>({...option,name:SKILLS.find(skill=>skill.id===option.id)?.name??option.name}));}if(choice.type==='choose_feat'&&!options.length)options=catalog.feats.map(f=>({id:f.id,name:f.name,description:cleanDescription(f.description,100),prerequisites:f.prerequisites}));if(['choose_cantrip','choose_spell'].includes(choice.type)&&!options.length)options=catalog.spells.filter(s=>s.level===(choice.type==='choose_cantrip'?0:1)&&(!choice.classId||s.availableToClasses.includes(choice.classId))).map(s=>({id:s.id,name:s.name,description:s.school}));
    if(choice.type==='choose_language'&&!options.length)return <LanguageChoice key={choice.id} choice={choice} selected={selected} character={c} catalog={catalog} onSelect={values=>set(choice,values)}/>;
    if(choice.type==='choose_ability_increase'&&choice.amount===1&&choice.options.every(option=>typeof option!=='string'&&!!option.effects?.length&&option.effects.every(effect=>effect.type==='ability_bonus'&&effect.ability&&typeof effect.value==='number')))return <AbilityIncreaseChoice key={choice.id} choice={choice} selected={selected} onSelect={values=>set(choice,values)}/>;
    if(choice.type==='asi'){const feat=selected[0]?.startsWith('feat:');const inc=selected.filter(s=>s.startsWith('ability:'));return <div className="choice-group" key={choice.id}><div className="choice-title"><h3>{choice.name}</h3><span className="badge">2 puntos o una dote</span></div><div className="inline-tabs"><button className={!feat?'active':''} onClick={()=>set(choice,[])}>Mejorar características</button><button className={feat?'active':''} onClick={()=>set(choice,['feat:'])}>Elegir dote</button></div>{feat?<select value={selected[0]||'feat:'} onChange={e=>set(choice,[e.target.value])} aria-label="Dote de mejora"><option value="feat:">Selecciona una dote</option>{catalog.feats.map(f=>{const why=checkPrerequisites(f.prerequisites,c,catalog);return <option value={`feat:${f.id}`} key={f.id} disabled={why.length>0}>{f.name}{why.length?` · ${why.join(', ')}`:''}</option>})}</select>:<div className="grid-3">{ABILITIES.map(a=>{const count=inc.filter(x=>x===`ability:${a.id}`).length;return <div className="panel" style={{padding:13}} key={a.id}><strong className="subtle">{a.label}</strong><div className="between" style={{marginTop:8}}><button className="icon-button" aria-label={`Reducir mejora ${a.label}`} disabled={!count} onClick={()=>{const v=[...inc];v.splice(v.indexOf(`ability:${a.id}`),1);set(choice,v)}}><Minus size={14}/></button><strong>+{count}</strong><button className="icon-button" aria-label={`Mejorar ${a.label}`} disabled={inc.length>=2} onClick={()=>set(choice,[...inc,`ability:${a.id}`])}><Plus size={14}/></button></div></div>})}</div>}</div>}
    const isExpertise=choice.type==='expertise'||choice.options.some(option=>typeof option!=='string'&&option.effects?.some(effect=>effect.type==='skill_expertise'));const free=options.length===0&&!isExpertise;const shown=options.filter(o=>(o.name+' '+o.description).toLocaleLowerCase('es').includes((filter[choice.id]||'').toLocaleLowerCase('es')));
    return <div className="choice-group" key={choice.id}><div className="choice-title"><h3>{choice.name}</h3><span className="badge">{selected.filter(Boolean).length} / {choice.amount}</span></div>{choice.source&&<SourceTag source={choice.source}/>}<div style={{height:9}}/>{isExpertise&&<p className="subtle" style={{marginBottom:12}}>Solo aparecen las habilidades y herramientas con las que ya tienes competencia.{!options.length?' Elige primero tus competencias en el paso anterior.':''}</p>}{free?<Field label={choice.type==='choose_language'?'Idiomas elegidos':'Elección manual'} hint={`Introduce ${choice.amount} ${choice.amount===1?'opción':'opciones'}, separadas por comas. Consulta el rasgo y acuerda las opciones con tu DM.`}><input value={selected.join(', ')} onChange={e=>set(choice,e.target.value.split(',').map(s=>s.trimStart()))}/></Field>:<>{options.length>12&&<div className="search-field" style={{marginBottom:12}}><Search size={16}/><input placeholder="Filtrar opciones…" value={filter[choice.id]||''} onChange={e=>setFilter({...filter,[choice.id]:e.target.value})}/></div>}<div className={options.length>25?'stack':'choice-options'} style={options.length>12?{maxHeight:330,overflowY:'auto',padding:2}:undefined}>{shown.map(o=>{const isSelected=selected.includes(o.id),why=checkPrerequisites(o.prerequisites||[],c,catalog),entity=catalog.features.find(x=>x.id===o.id)||catalog.feats.find(x=>x.id===o.id)||catalog.spells.find(x=>x.id===o.id)||catalog.classes.flatMap(cl=>cl.subclasses).find(x=>x.id===o.id);return <div key={o.id} className="flex" style={{alignItems:'stretch',gap:3}}><CheckOption selected={isSelected} disabled={!isSelected&&why.length>0} onClick={()=>set(choice,isSelected?selected.filter(v=>v!==o.id):choice.amount===1?[o.id]:selected.length<choice.amount?[...selected,o.id]:selected)} title={o.name} description={why.length?why.join(' · '):o.description?cleanDescription(o.description,110):undefined}/>{entity&&<button className="icon-button" aria-label={`Ver ${o.name}`} onClick={()=>setDetail(entity)}><Info size={15}/></button>}</div>})}</div></>}</div>
  })}<Modal open={!!detail} onClose={()=>setDetail(null)} title={detail?.name||''} wide>{detail&&(catalog.races.some(r=>r.id===detail!.id)?<RaceDetails race={catalog.races.find(r=>r.id===detail!.id)!} catalog={catalog}/>:<><SourceTag source={detail.source}/><p className="source-prose">{detail.description}</p></>)}</Modal></>
}

export function SpellPicker({character:c,catalog,onChange}:EditorProps){const d=deriveCharacter(c,catalog),[query,setQuery]=useState(''),[classId,setClassId]=useState(c.classes[0]?.classId||''),[level,setLevel]=useState('all'),[detail,setDetail]=useState<Spell|null>(null);const caster=d.spellcasting.find(s=>s.classId===classId)||d.spellcasting[0];
  if(!caster)return <Empty icon={<BookOpen size={27}/>} title="Tu aventura no requiere un grimorio" description="Tu clase aún no tiene lanzamiento de conjuros. Los trucos de origen se eligen en Opciones."/>;
  const id=caster.classId,sel=c.spellSelections[id]||{known:[],prepared:[]},spells=validSpells(c,id,catalog),granted=getClassGrantedSpells(c,id,catalog),grantedIds=new Set(granted.map(s=>s.id)),fixedCantrips=getFixedClassCantrips(c,id,catalog),cls=catalog.classes.find(x=>x.id===id),counts={cantrips:new Set([...sel.known.filter(s=>catalog.spells.find(x=>x.id===s)?.level===0),...fixedCantrips.map(s=>s.id)]).size,spells:sel.known.filter(s=>(catalog.spells.find(x=>x.id===s)?.level||0)>0&&!grantedIds.has(s)).length};
  const toggle=(spell:Spell)=>{if(grantedIds.has(spell.id))return;const chosen=sel.known.filter(x=>!grantedIds.has(x)),known=chosen.includes(spell.id)?chosen.filter(x=>x!==spell.id):[...chosen,spell.id];onChange({...c,spellSelections:{...c.spellSelections,[id]:{known,prepared:sel.prepared.filter(x=>known.includes(x))}}})};
  const options=[...new Map([...spells,...granted].filter(s=>!fixedCantrips.some(fixed=>fixed.id===s.id)&&s.name.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))&&(level==='all'||s.level===Number(level))).map(s=>[s.id,s])).values()];
  return <div className="stack"><div className="inline-tabs">{d.spellcasting.map(sc=><button className={id===sc.classId?'active':''} key={sc.classId} onClick={()=>setClassId(sc.classId)}>{catalog.classes.find(x=>x.id===sc.classId)?.name}</button>)}</div><div className="grid-3"><div className="badge">Trucos: {counts.cantrips} / {caster.cantrips??'manual'}</div><div className="badge">{cls?.spellcasting?.mode==='spellbook'?'En el libro':'Conocidos'}: {counts.spells} / {caster.knownLimit??(spellbookMinimum(c,id,catalog)!==null?'mín. '+spellbookMinimum(c,id,catalog):'selección libre')}</div><div className="badge">Preparados: {sel.prepared.length} / {caster.preparedLimit??'no aplica'}</div></div><label className="flex subtle"><input type="checkbox" checked={c.choices[`optional-spells.${id}`]?.includes('enabled')||false} onChange={e=>onChange({...c,choices:{...c.choices,[`optional-spells.${id}`]:e.target.checked?['enabled']:[]}})}/>Permitir ampliaciones opcionales de Tasha (con acuerdo del DM)</label><div className="library-tools"><div className="search-field"><Search size={16}/><input placeholder="Buscar hechizo…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Nivel de hechizo" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Todos los niveles</option>{Array.from({length:caster.maxSpellLevel+1},(_,i)=><option key={i} value={i}>{i?'Nivel '+i:'Trucos'}</option>)}</select></div><div className="stack" style={{maxHeight:460,overflowY:'auto',padding:2,gap:8}}>{fixedCantrips.map(s=><div className="badge" key={s.id}>{s.name} · Truco concedido por la subclase</div>)}{options.map(s=><div className="flex" key={s.id} style={{gap:5}}><CheckOption selected={grantedIds.has(s.id)||sel.known.includes(s.id)} disabled={grantedIds.has(s.id)} onClick={()=>toggle(s)} title={s.name} description={`${s.level===0?'Truco':'Nivel '+s.level} · ${s.school} · ${s.castingTime}${grantedIds.has(s.id)?' · Concedido por la subclase':''}${(s as Spell&{optionalForClasses?:string[]}).optionalForClasses?.includes(id)?' · Opcional Tasha':''}`}/><button className="icon-button" aria-label={`Descripción de ${s.name}`} onClick={()=>setDetail(s)}><BookOpen size={16}/></button>{caster.preparedLimit!==null&&s.level!==0&&sel.known.includes(s.id)&&!grantedIds.has(s.id)&&<button className={`button compact ${sel.prepared.includes(s.id)?'primary':''}`} onClick={()=>onChange({...c,spellSelections:{...c.spellSelections,[id]:{...sel,prepared:sel.prepared.includes(s.id)?sel.prepared.filter(x=>x!==s.id):[...sel.prepared,s.id]}}})}>{sel.prepared.includes(s.id)?'Preparado':'Preparar'}</button>}</div>)}</div>{options.length===0&&fixedCantrips.length===0&&<p className="subtle">No hay conjuros que coincidan con estos filtros.</p>}<Modal open={!!detail} onClose={()=>setDetail(null)} title={detail?.name||''} wide>{detail&&<SpellDetails spell={detail}/>}</Modal></div>
}

export function IdentityEditor({character:c,onChange}:EditorProps){const setBio=(key:string,value:string)=>onChange({...c,biography:{...c.biography,[key]:value}});return <div className="stack"><div className="grid-2"><Field label="Nombre"><input value={c.name} maxLength={120} onChange={e=>onChange({...c,name:e.target.value})}/></Field><Field label="Retrato" hint="PNG, JPG o WebP, hasta 1 MB. Se guarda con el personaje."><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024){e.target.setCustomValidity('El retrato debe ocupar menos de 1 MB.');e.target.reportValidity();return}e.target.setCustomValidity('');const reader=new FileReader();reader.onload=()=>onChange({...c,portrait:String(reader.result)});reader.readAsDataURL(file)}}/></Field>{c.portrait&&<div className="flex"><img src={c.portrait} alt="Retrato" style={{height:75,width:64,objectFit:'cover',borderRadius:5}}/><Button variant="ghost" className="compact" onClick={()=>onChange({...c,portrait:''})}>Quitar retrato</Button></div>}</div><div className="grid-3">{['Edad','Altura','Peso','Ojos','Piel','Cabello','Alineamiento','Deidad'].map(label=><Field label={label} key={label}><input value={c.biography[label.toLowerCase()]||''} onChange={e=>setBio(label.toLowerCase(),e.target.value)}/></Field>)}</div><div className="grid-2">{[['historia','Historia'],['apariencia','Apariencia'],['personalidad','Personalidad'],['ideales','Ideales'],['vinculos','Vínculos'],['defectos','Defectos'],['organizaciones','Organizaciones'],['aliados','Aliados'],['enemigos','Enemigos']].map(([key,label])=><Field label={label} key={key}><textarea value={c.biography[key]||''} onChange={e=>setBio(key,e.target.value)}/></Field>)}</div></div>}
